### ISSUE TITLE
Update application

### ISSUE THREAD

**Issue by r1soX** [Shiyan7/kinomore-v2#20]
When is the new update?

**Comment by r1soX** [comment]
Hey?

**Comment by Shiyan7** [comment]
Hello) when there is free time, maybe in a month or two a new design will be ready

**Comment by r1soX** [comment]
I'm still waiting for updates, at least where there will be posters in the images tab, etc., can you do it?

**Comment by Shiyan7** [comment]
Yes, later)

**Comment by r1soX** [comment]
I'll be waiting :-)

**Comment by r1soX** [comment]
I'm still waiting for an update :)))

**Comment by Shiyan7** [comment]
если ты хочешь можешь создать ветку и в ней сделать эту фичу я пока работаю

**Comment by r1soX** [comment]
Crashes from the profile when you log in to it

**Comment by Shiyan7** [comment]
> Crashes from the profile when you log in to it

fixed)
